[package]
name = "demos"
version = "0.1.0"
edition = "2024"

[dev-dependencies]
criterion = {version = "0.5", features = ["html_reports"]}

[dependencies]
rayon = "1.10"
dhat = { version = "0.3", optional = true }
rand = "0.9"
smallvec = "1.13"

[features]
dhat-heap = ["dep:dhat"]

[profile.release]
debug = true
[[bench]]
name="bench_demo01"
harness= false

[[bench]]
name="bench_exo01"
harness= false
